version: '3'

services:
  db:
    image: postgres:latest
    network_mode: host
    environment:
      - ENV LANG=pt_BR.UTF-8
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432